name: Build Grocery MAUI App (Android + iOS)

on:
  push:
    branches: [ main, hotfix ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          global-json-file: global.json

      - name: Show SDK
        run: dotnet --info

      - name: Install MAUI Android workload
        run: dotnet workload install maui maui-android

      - name: Restore (Android only)
        run: dotnet restore Grocery.App/Grocery.App.csproj -f net8.0-android

      - name: Build (Android)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-android --no-restore

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          global-json-file: global.json

      - name: Show SDK
        run: dotnet --info

      - name: Install MAUI iOS workload
        run: dotnet workload install maui maui-ios

      - name: Restore (iOS only)
        run: dotnet restore Grocery.App/Grocery.App.csproj -f net8.0-ios

      - name: Build (iOS)
        run: dotnet build Grocery.App/Grocery.App.csproj -c Release -f net8.0-ios --no-restore
